# Generated by Django 4.2.5 on 2023-09-20 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypesL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_l', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64)),
                ('teacher', models.CharField(max_length=64)),
                ('time_s', models.TimeField()),
                ('time_e', models.TimeField()),
                ('cabinet', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayname', to='timetable.days')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupname', to='timetable.group')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typename', to='timetable.typesl')),
            ],
        ),
    ]
